### ISSUE TITLE
Update readme with projects that have been moved already

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/td-tools#13]
https://github.com/eclipse-thingweb/td-tools/blob/main/README.md informs about the idea to move certain projects.

Since some tools exists already we ought to update the README

**Comment by egekorkan** [comment]
Done via https://github.com/eclipse-thingweb/td-tools/commit/ee21893c6595d9e458cc28820e1e913c61e064a5

For subsequent transfers, let's do this with the initial PR.
