### ISSUE TITLE
Introduce a proper CI check for building and testing PRs

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/td-tools#16]
As demonstrated with https://github.com/eclipse-thingweb/td-tools/pull/15 there is no CI check that shows test or build failures.

**Comment by egekorkan** [comment]
Given that we have different and independent tools, I propose to have separate ci files per tool and start only the relevant one based on the changes. Any thoughts?

**Comment by egekorkan** [comment]
We should be able to do it folder based on paths option https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
