### ISSUE TITLE
New package for td-utils

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/td-tools#18]
> We will create a package in td-tools that has such helper functions and then deprecate the functions here. Also, the function in https://github.com/eclipse-thingweb/playground/blob/master/packages/core/index.js#L1293 will be moved there and published. It can be more flexible with some filters like "find it only in properties".

td-utils will be the new package name and can contain such tools. It should return an object with binding name as keys (just http, opc etc) then inside it found uri scheme (http, https, mqtt+ws) and subprotocol.

_Originally posted by @egekorkan in https://github.com/eclipse-thingweb/node-wot/issues/1270#issuecomment-2079025156_

**Comment by egekorkan** [comment]
These should be small functions to extract information out of TDs. Anything that is not transforming or validating TDs.

**Comment by hasanheroglu** [comment]
I will take care of this.

**Comment by egekorkan** [comment]
After discussing with @hasanheroglu , we should also find the hostname since it will be relevant when connecting to the broker in MQTT (like in https://github.com/eclipse-thingweb/node-wot/blob/master/packages/binding-mqtt/src/mqtt-client.ts#L55)
