### ISSUE TITLE
Moving thing-model-helpers from node-wot

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/td-tools#23]
As agreed today, we can move https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/thing-model-helpers.ts here.

This means creating the folder, CI pipeline, test. Then deleting from node-wot. Then publishing to npm with name `@thingweb/tm-helpers` and adjusting imports in playground.

@hasanheroglu will tackle this

**Comment by hasanheroglu** [comment]
I will take care of this.
