### ISSUE TITLE
Moving JSON Schema based spell checker from playground

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/td-tools#26]
https://github.com/eclipse-thingweb/playground/tree/master/packages/json-spell-checker should be moved here by doing the necessary adjustments like in https://github.com/eclipse-thingweb/td-tools/issues/23 (publishing, deleting etc.) with name `@thingweb/json-spell-checker`

**Comment by hasanheroglu** [comment]
I will take care of this.
