### ISSUE TITLE
Project structure and package name

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/td-tools#3]
We have to decide:
- the npm root name and the subprojects. 
- [README](https://github.com/eclipse-thingweb/td-tools/blob/main/README.md) already mentions a list of possible projects but what is the directory structure? 
- Is `gitsubmodules` still an option? or npm workspaces? 
- Understand dependencies between tools

**Comment by egekorkan** [comment]
@danielpeintner will detail what the other scripts within node-wot/td-tools do

**Comment by danielpeintner** [comment]
Please find below a proposal how to restructure "td-tools" related code:

- eclipse-thingweb/node-wot
  - remove folder `eclipse-thingweb/node-wot/packages/td-tools` entirely
  - `eclipse-thingweb/node-wot/packages/core` should link to `eclipse-thingweb/td-tools/node/foundation` (see newly created package below)
- eclipse-thingweb/td-tools
  - create project `eclipse-thingweb/td-tools/node/foundation` (_all open for a better name_) with
    - [thing-description.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/thing-description.ts) 
    - [td-parser.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/td-parser.ts) // _maybe rename it since it is a serializer as well or split the functionality_
    - [resolver-interface.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/resolver-interface.ts) // _not sure whether we actually need this interface used by helpers and thing-model_
    - [td-helpers.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/td-helpers.ts)  // _has little functionality, maybe can be moved into node-wot/core_
  - create project `eclipse-thingweb/td-tools/node/thing-model` with
    -  [thing-model-helpers.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/thing-model-helpers.ts)
  - create project `eclipse-thingweb/td-tools/node/aid` with
    -  [asset-interface-description.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/util/asset-interface-description.ts)
  - create other projects w.r.t. validation etc from playground ...

Any opinions/suggestions?

**Comment by egekorkan** [comment]
I quite like the proposal. The main confusing part is how to explain what the "foundation" package offers to outsiders so I am not able to provide an alternative name :/

**Comment by egekorkan** [comment]
- npm packages variations: 
  - `@eclipse-thingweb/td-tools/thing-model-helpers`
  - `@thingweb/td-tools/thing-model-helpers` -> may not be allowed
  - `@thingweb/td-tools-thing-model-helpers`
  - `@thingweb/thing-model-helpers`
  - `@thingweb/tm-helpers`
  - `@thingweb/node-wot-binding-http`
  - `@thingweb/node-wot-contrib-binding-x`
  - Note: `@` is not governed or restricted but we should check

Decision on renaming: we will have `@thingweb/TOOL_NAME`

**Comment by sebastiankb** [comment]
When will the new structure be applied?

**Comment by egekorkan** [comment]
> When will the new structure be applied?

- I can move playground tools in one PR with renaming before January. For node-wot "foundation" package we need more discussion.
- thing-model should be called tm-helpers, foundation can be td-helpers if we want to.
- The goal is having one package that does "parsing", i.e. canonicalization by adding all needed defaults. This needed before consuming. It is validation + adding defaults imo.
  - There is a refactoring need. In node-wot, there are multiple places where validation and defaults happen. (parser, init exposed thing, bindings for protocol defaults)

**Comment by danielpeintner** [comment]
I sketched how I "see" the best way forward in https://github.com/eclipse-thingweb/td-tools/issues/3#issuecomment-1816398949
We (I) can try to describe next year ;-) the relations and it current usage...

**Comment by egekorkan** [comment]
node-wot td parser:
Consuming:
- It corrects user inputs (if readonly is not boolean, it is corrected to boolean)
- Fills defaults

For the future, the core package can do this, meaning td-parser is not necessary for an outsider as a tool

- At the same time, we should align the default addition mechanism to use ajv and share the library between playground web and node-wot
- We can reuse the validation library after https://github.com/eclipse-thingweb/node-wot/blob/8adf8406c395e01fcd9d38f20af59aae96220182/packages/core/src/helpers.ts#L59 (that line is doing a partial TD validation so it is not same validation)

**Comment by egekorkan** [comment]
The overall structure is now applied. I will open new issues for default handling and validation
