### ISSUE TITLE
Exporting the Resolver Interface

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/td-tools#35]
This https://github.com/eclipse-thingweb/td-tools/blob/main/node/thing-model/src/tm-helpers.ts#L27 was meant to be publicly exported so that other can provide resolvers.

**Comment by danielpeintner** [comment]
Not fully handled yet .. will create yet another PR

![image](https://github.com/user-attachments/assets/a91d2b7c-aaf8-465a-94d0-edd5a4a4d107)
