### ISSUE TITLE
[AID] SecurityConfiguration value has no idShort

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/td-tools#51]
Using the following TD:

```json
{
    "@context": [
        "https://www.w3.org/2022/wot/td/v1.1"
    ],
    "title": "test",
    "securityDefinitions": {
        "nosec_sc": {
            "scheme": "nosec"
        }
    },
    "base": "http://example.com",
    "security": [
        "nosec_sc"
    ],
    "properties": {
        "frequency": {
            "type": "number",
            "forms": [
                {
                    "href": "/test",
                    "contentType": "application/json"
                }

            ]
        }
    }
}
```

The generated AID, just below line 107 in [Playground](https://playground.thingweb.io/), there is no `idShort` generated inside that value. So there should be a value at `submodelElements[0].value[1].value[1].value[0]`

**Comment by egekorkan** [comment]
@kaz040 will check this since idShort should not be mandatory in this case.

**Comment by Kaz040** [comment]
@egekorkan , I just checked, for now I think everything is ok.

1. According to the specification (p. 194), The idShort of elements in a submodelElementList should not be specified 
  
![image](https://github.com/user-attachments/assets/04f214dd-5fe7-4b5c-a648-3f3a0ce4f12d)

2. literally, the element in the security submdelElementList is a referenceElement. so the element that it is referencing (from image below) has IdShort and other informations....

<img width="808" alt="Security" src="https://github.com/user-attachments/assets/94772f1e-84bb-413f-99de-28e71d815242">

**Comment by danielpeintner** [comment]
@egekorkan @Kaz040 your findings show that we can close the issue, right?

**Comment by egekorkan** [comment]
Indeed, closing as no fix is needed

**Comment by egekorkan** [comment]
Apparently the problem might be slightly different. Reopening

**Comment by wiresio** [comment]
@Kaz040 - thanks for clarifying! As an additional question I would like to ask whether the "ReferenceElement" list is the correct way for the security element. If yes, then I have an issue in my own implementation at https://github.com/wiresio/domus-tdd-api-plugin-aid :-) and this one can really be closed.

**Comment by Kaz040** [comment]
The Security SML can contain list of reference(s) (referenceElement(s)) that reference securities defined in securityDefinition SMC.

**Comment by wiresio** [comment]
Thanks, let's close here. I'll open an issue for myself ;-)
